env:
  browser: true
  commonjs: true
  amd: true
  es6: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - warn
    - 4
    - SwitchCase: 1
  linebreak-style:
    - warn
    - unix
  semi:
    - warn
    - always

  quotes: 0
  no-console: 0
  react/jsx-uses-react: 1
  react/jsx-uses-vars: 1
  react/react-in-jsx-scope: 1
